services:
  db:
    image: mysql:8.2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'manpar'
      MYSQL_ROOT_PASSWORD: '13angulo'
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p13angulo || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: manpar
      DB_USER: root
      DB_PASSWORD: 13angulo
      DB_HOST: db
      DB_PORT: 3306
