# Generated by Django 5.0.7 on 2024-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderitem_observations_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishImg',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
