# Generated by Django 5.0.7 on 2024-08-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dish_dishimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dishImg',
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.dish')),
            ],
        ),
    ]
