# Generated by Django 5.0.7 on 2024-08-02 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orderitem_created_at_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='api.table'),
        ),
    ]
