# Generated by Django 5.0.7 on 2024-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bill_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
