# Generated by Django 5.0.7 on 2024-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_period',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('B', 'Both')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
